#!/usr/bin/env ansible-playbook
---
- hosts: pis
  gather_facts: yes
  vars:
    #wifi:
      #ssid: "enter ssid"
      #password: enter password
    install_pkgs: [ git, node, npm, python, vim ]
    #pip_packages_to_install: [ awscli ]
    #npm_packages_to_install: [  ]
    update_cache: no
  become: yes
  tasks:
    #- name: configure wifi
    #  template: src=templates/wpa_supplicant.conf dest=/etc/wpa_supplicant/wpa_supplicant.conf
    #  notify: reboot

    - name: install packages
      apt:
        pkg: "{{ item }}"
        state: latest
      with_items: "{{ install_pkgs }}"

    #- name: install python modules with pip
    #  pip: name={{ item }}
    #  with_items: pip_packages_to_install

    #- name: install node.js packages with npm
    #  npm: name={{ item }} global=yes
    #  with_items: npm_packages_to_install

  handlers:
    - name: reboot
      command: shutdown -r now "Ansible setup ..."
      async: 0
      poll: 0
      ignore_errors: true
